openapi: "3.0.0"
info:
  title: "Realtime ELO Ranker API"
  description: "API documentation for the Realtime ELO Ranker"
  version: "0.1.0"
servers:
  - url: "http://localhost:8080"
    description: "Local server"
paths:
  # --- MATCHS ---
  /api/match:
    post:
      summary: "Publication des résultats d'un match"
      description: |
        Publie les résultats d'un match pour mettre à jour le classement des joueurs.
        Si le match s'est terminé par un match nul, le champ `draw` doit être `true`.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                winner:
                  type: "string"
                  description: "L'identifiant (nom) du gagnant"
                loser:
                  type: "string"
                  description: "L'identifiant (nom) du perdant"
                draw:
                  type: "boolean"
                  description: "Indique si le match s'est terminé par un match nul"
      responses:
        201:
          description: "Résultats du match publiés avec succès"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchResult"
        422:
          description: "Joueur introuvable"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  # --- JOUEURS ---
  /api/player:
    post:
      summary: "Création d'un joueur"
      description: "Crée un nouveau joueur avec un ELO initial."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                id:
                  type: "string"
                  description: "L'identifiant du joueur (son nom d'utilisateur)"
      responses:
        201:
          description: "Joueur créé avec succès"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"
        409:
          description: "Le joueur existe déjà"
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/Error"
    get:
      summary: "Récupérer tous les joueurs"
      description: "Retourne la liste complète des joueurs et leur classement."
      responses:
        200:
          description: "Liste récupérée avec succès"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Player"

  /api/player/{id}:
    get:
      summary: "Récupérer un joueur"
      description: "Retourne les détails d'un joueur spécifique par son ID (nom)."
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: "L'identifiant du joueur (nom)"
      responses:
        200:
          description: "Joueur trouvé"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"
        404:
          description: "Joueur introuvable"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  # --- CLASSEMENT & SSE ---
  /api/ranking:
    get:
      summary: "Récupération du classement"
      description: "Récupère le classement des joueurs trié par ELO."
      responses:
        200:
          description: "Classement récupéré avec succès"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Player"

  /api/ranking/events:
    get:
      summary: "Flux SSE du classement"
      description: |
        Abonnement Server-Sent Events (SSE) pour recevoir les mises à jour du classement en temps réel.
      responses:
        200:
          description: "Connexion SSE établie"
          content:
            text/event-stream:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/RankingUpdate"
                  - $ref: "#/components/schemas/Error"

components:
  schemas:
    Player:
      type: "object"
      required:
        - id
        - rank
      properties:
        id:
          type: "string"
          description: "L'identifiant du joueur (Username)"
        rank:
          type: "number"
          description: "Le classement ELO du joueur"
    
    MatchResult:
      type: "object"
      required:
        - winner
        - loser
      properties:
        winner:
          $ref: "#/components/schemas/Player"
        loser:
          $ref: "#/components/schemas/Player"
    
    RankingEvent:
      type: "object"
      required:
        - type
      properties:
        type:
          type: "string"
          description: "Le type d'événement"
    
    RankingUpdate:
      allOf:
        - $ref: "#/components/schemas/RankingEvent"
        - type: "object"
          required:
            - player
          properties:
            type:
              value: "RankingUpdate"
            player:
              $ref: "#/components/schemas/Player"
    
    Error:
      type: "object"
      properties:
        statusCode:
          type: "number"
        message:
          type: "string"
        error:
          type: "string"